version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  config:
    image: melalex/zephyr-config
    restart: always
    ports:
      - "8888:8888"

  monitoring:
    image: melalex/zephyr-monitoring
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "9000:8080"
      - "8989:8989"

  registry:
    image: melalex/zephyr-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "8761:8761"