logging:
  level:
    org.springframework.security: INFO

security:
  oauth2:
    resource:
      user-info-uri: http://auth:5000/v1/users/current

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq
    password: ${RABBITMQ_PASSWORD:guest}
    username: ${RABBITMQ_USER:guest}
    port: 5672