server:
  port: 8011

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://auth-mysql:3306/zephyr?useSSL=false
    username: zephyr
    password: zephyr
    platform: mysql