server:
  port: 8012

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth:
      path: /auth/**
      url: http://auth:8011
      stripPrefix: false
      sensitiveHeaders:

#    agent:
#      path: /agent/**
#      serviceId: agent
#      stripPrefix: false
#      sensitiveHeaders:

    keyword:
      path: /keyword/**
      serviceId: keyword
      stripPrefix: false
      sensitiveHeaders:

    location:
      path: /location/**
      serviceId: location
      stripPrefix: false
      sensitiveHeaders:

    rating:
      path: /rating/**
      serviceId: rating
      stripPrefix: false
      sensitiveHeaders:

    task-service:
      path: /task/**
      serviceId: task
      stripPrefix: false
      sensitiveHeaders: