spring:
  cloud:
    stream:
      bindings:
        input:
          destination: KEYWORDS
        output:
          destination: SEARCH_RESULTS

browser:
  backoff: 5000
  retryCount: 2

scraper:
  google:
    enabled: true
    saveResponse: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#rso > div > div > div> div > div > div > div > div.f.kv._SWb > cite"
    first: 0
    resultCount: 100
    pageSize: 100
    requestType: DIRECT

  bing:
    enabled: true
    saveResponse: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#b_results > li > h2 > a"
    first: 1
    resultCount: 10
    pageSize: 10
    requestType: DIRECT

  yahoo:
    enabled: true
    saveResponse: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#web > ol > li > div > div > div > span"
    first: 1
    resultCount: 10
    pageSize: 10
    requestType: DIRECT

  yandex:
    enabled: false
    saveResponse: false
    delay: 480000
    errorDelay: 480000
    linkSelector:
    first: 0
    resultCount: 100
    pageSize: 100
    requestType: DIRECT

  duckduckgo:
    enabled: false
    saveResponse: false
    delay: 480000
    errorDelay: 480000
    linkSelector:
    first: 0
    resultCount: 100
    pageSize: 100
    requestType: DIRECT