server:
  port: 8017

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: QUERIES

  data:
    mongodb:
      host: task-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: task
      port: 27017

task:
  cron: 0 0 0 1/1 * ?
  batchSize: 100
  enableUpdates: false
  relevancePeriod:
    days: 3
    hours: 0
    minutes: 0
    seconds: 0