server:
  port: 8011

spring:
  application:
    name: config
    index: ${random.uuid}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melalex/zephyr-config
        native:
          search-locations: classpath:/shared

security:
  user:
    password: ${CONFIG_SERVER_PASSWORD}